//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuartzSchedulerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobParams = new HashSet<JobParam>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string GroupName { get; set; }
        public string JobName { get; set; }
        public string JobType { get; set; }
        public string CronExpression { get; set; }
        public string TriggerGroup { get; set; }
        public bool Enabled { get; set; }
        public string Details { get; set; }
        public string TriggerName { get; set; }
    
        public virtual JobType Type { get; set; }
        public virtual ICollection<JobParam> JobParams { get; set; }
    }
}
