//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuartzSchedulerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobType
    {
        public JobType()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string TypeAssembly { get; set; }
        public string ParamKeys { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
